#!/bin/bash
# See: https://github.com/pr3d4t0r/COVIDvu/blob/master/LICENSE 
# vim: set fileencoding=utf-8:


source ./pyrunner


# *** main ***

# TODO: fix this 'keep' flag - not needed later
python3 -m covidvu.pipeline.jsonpack keep
ls -Alrt "$SITE_DATA_DIR"/*json

