#!/bin/bash

# See: https://github.com/VirusTrack/COVIDvu/blob/master/LICENSE 
# vim: set fileencoding=utf-8:

# crontab compliant :)


source ./pyrunner


python -m covidvu.pipeline.vudpatch confirmed deaths recovered

ls -Alrt "$SITE_DATA_DIR"/*json

