#!/bin/bash
# See: https://github.com/VirusTrack/COVIDvu/blob/master/LICENSE 
# vim: set fileencoding=utf-8:

source ./pyrunner

env | awk '/VIRT/' | sort
python3 -m covidvu.pipeline.vujson confirmed deaths recovered
ls -Alrt "$SITE_DATA_DIR"

