#!/bin/bash
# See: https://github.com/pr3d4t0r/COVIDvu/blob/master/LICENSE 
# vim: set fileencoding=utf-8:


REFRESHDATA_CONFIG="./refreshdata.config"
[[ -e "$REFRESHDATA_CONFIG" ]] && source "$REFRESHDATA_CONFIG"

source ./pyrunner

export COUNTY_CASES_US_ENDPOINT="https://coronavirus-tracker-api.herokuapp.com/v2/locations?source=csbs"


# *** main ***

echo "fetchcing counties data from $COUNTY_CASES_US_ENDPOINT"

curl -A "$PYAVKA_USER_AGENT" -s "$COUNTY_CASES_US_ENDPOINT" | jq -M '.locations' > "$COUNTY_CASES_CSBS_FILE" 

python -m covidvu.pipeline.vucounty
python -m covidvu.pipeline.vuhospitals

