#!/bin/bash
# See: https://github.com/VirusTrack/COVIDvu/blob/master/LICENSE 
# vim: set fileencoding=utf-8:


REFRESHDATA_CONFIG="./refreshdata.config"
[[ -e "$REFRESHDATA_CONFIG" ]] && source "$REFRESHDATA_CONFIG"

source "./vucommon.bash"
source ./pyrunner

export COUNTY_CASES_US_ENDPOINT="https://coronavirus-tracker-api.herokuapp.com/v2/locations?source=csbs"
export CASES_OUTPUT="/tmp/countyraid.json"


# *** main ***


echo "fetchcing counties data from $COUNTY_CASES_US_ENDPOINT"

assertDatabaseOK

curl -A "$PYAVKA_USER_AGENT" -s "$COUNTY_CASES_US_ENDPOINT" > "$CASES_OUTPUT"

status="$?"
[[ "$status" == "0" ]] || die "Unable to fetch counties data - error $status - output: $CASES_OUTPUT" 1

cat "$CASES_OUTPUT" | jq -M '.locations' > "$COUNTY_CASES_CSBS_FILE" 

python -m covidvu.pipeline.vucounty
python -m covidvu.pipeline.vuhospitals

