#!/bin/bash
# See: https://github.com/pr3d4t0r/COVIDvu/blob/master/LICENSE 
# vim: set fileencoding=utf-8:


source ./pyrunner


# *** main ***

python3 -m covidvu.pipeline.jsonpack
ls -Alrt "$SITE_DATA_DIR"/bundle*json

