#!/bin/bash
# See: https://github.com/pr3d4t0r/COVIDvu/blob/master/LICENSE 
# vim: set fileencoding=utf-8:


RAW_DATA_SOURCE="https://docs.google.com/spreadsheets/d/e/2PACX-1vR30F8lYP3jG7YOq8es0PBpJIE5yvRVZffOyaqC0GgMBN6yt0Q-NI8pxS7hd1F9dYXnowSC6zpZmW9D/pubhtml?gid=0&amp;single=false&amp;widget=true&amp;headers=true"


# *** main ***

curl -s "$RAW_DATA_SOURCE" | \
    awk '/<table/ { gsub("<table", "\n<table"); gsub("\/table>", "/table>\n"); print; }' | \
    awk '/<table/ { o = sprintf("t-%02d.html", n++); print > o; close(o); }'

