#!/bin/bash
# See: https://github.com/pr3d4t0r/COVIDvu/blob/master/LICENSE 
# vim: set fileencoding=utf-8:


source ./pyrunner


HTML_FILE_NAME="$SITE_DATA_DIR/table-%02d.html"
RAW_DATA_SOURCE="https://docs.google.com/spreadsheets/d/e/2PACX-1vR30F8lYP3jG7YOq8es0PBpJIE5yvRVZffOyaqC0GgMBN6yt0Q-NI8pxS7hd1F9dYXnowSC6zpZmW9D/pubhtml?gid=0&amp;single=false&amp;widget=true&amp;headers=true"
RAW_DATA_FILE="$SITE_DATA_DIR/raw-source.html"
PYAVKA_USER_AGENT="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:74.0) Gecko/20100101 Firefox/74.0"


# ::: functions :::

function fetchBNODataSource {
    echo "-----"
    curl -A "$PYAVKA_USER_AGENT" -vi -o "$RAW_DATA_FILE" --connect-timeout 20 "$RAW_DATA_SOURCE" | 
    [[ "$?" == 0 ]] || exit 99

    cat "$RAW_DATA_FILE" | awk '/<table/ { gsub("<table", "\n<table"); gsub("/table>", "/table>\n"); print; }' | \
    awk -v "H=$HTML_FILE_NAME" '/<table/ { o = sprintf(H, n++); print > o; close(o); }'

    echo "+++++"
} # fetchBNODataSource


# *** main ***

fetchBNODataSource
python3 -m covidvu.pipeline.pyavka

