#!/bin/bash
# See: https://github.com/VirusTrack/COVIDvu/blob/master/LICENSE 
# vim: set fileencoding=utf-8:


REFRESHDATA_CONFIG="./refreshdata.config"
[[ -e "$REFRESHDATA_CONFIG" ]] && source "$REFRESHDATA_CONFIG"


# *** functions ***

function die {
    echo "[Error $2] - $1" 
    exit "$2"
} # die


function assertContainerSigFileIsDefined {
    if [[ -n "$CLICOLOR" ]] # in Jupyter environment only
    then
        return
    fi

    local cwd=$(pwd)
    echo "  asserting CONTAINER_SIG_FILE exists (Now: $cwd)"
    [[ -n "$CONTAINER_SIG_FILE" ]] || die "CONTAINER_SIG_FILE environment variable undefined" 2
} # assertContainerSigFileIsDefined


function runtimePythonEnvironment {
    if [[ -n "$CLICOLOR" ]] # in Jupyter environment only
    then
        return
    fi

    if [[ -n "$VIRTUAL_ENV" ]]
    then
        echo "  already in Python virtual environment"
        return
    fi

    echo "  not VIRTUAL_ENV"
    if [[ "Linux" == $(uname) ]]
    then
        echo "  host system: " $(uname) " looking for $CONTAINER_SIG_FILE"
        awk '/docker/ || /lxc/ { exit(99); }' "$CONTAINER_SIG_FILE"
        if [[ "$?" == 0 ]]
        then
            echo "activating the virtual environment"
            source ./bin/activate || die "unable to start virtualenv" 1
        fi
    fi
} # runtimePythonEnvironment


assertContainerSigFileIsDefined
runtimePythonEnvironment
# -------- DO NOT WRITE ANYTHING BELOW THIS LINE --------
