#!/bin/bash
# See: https://github.com/pr3d4t0r/COVIDvu/blob/master/LICENSE 
# vim: set fileencoding=utf-8:

source ./pyrunner

python3 -m covidvu.vujson confirmed deaths recovered
ls -Alrt "$SITE_DATA_DIR"

